-- Themery https://github.com/zaldih/themery.nvim

local theme_menu_items = {
    "aura-dark",
    "aura-dark-soft-text",
    "aura-soft-dark",
    "aura-soft-dark-soft-text",
    "ayu",
    "catppuccin-frappe",
    "catppuccin-macchiato",
    "catppuccin-mocha",
    "dracula",
    "edge",
    "ef-owl",
    "ef-winter",
    "eldritch",
    -- "everforest",
    "horizon-extended",
    "kanagawa-dragon",
    "kanagawa-lotus",
    "kanagawa-wave",
    "monokai",
    "moonfly",
    "nekonight-arcdark",
    "nekonight-aurora",
    "nekonight-day",
    "nekonight-deep-ocean",
    "nekonight-doom-one",
    "nekonight-dracula",
    "nekonight-dracula-at-night",
    "nekonight-fire-obsidian",
    "nekonight-material-theme",
    "nekonight-moon",
    "nekonight-moonlight",
    "nekonight-nord",
    "nekonight-onedark-deep",
    "nekonight-shades-of-purple",
    "nekonight-shades-of-purple-dark",
    "nekonight-night",
    "nekonight-noctis-uva",
    "nekonight-palenight",
    "nekonight-sky-blue",
    "nekonight-space",
    "nekonight-storm",
    "nekonight-synthwave",
    "nekonight-zenburn",
    "nightfly",
    "nordic",
    "onedark",
    -- "onedarkpro",
    "oxocarbon",
    "PaperColor",
    "palenightfall",
    "penumbra",
    "tokyonight-moon",
    "tokyonight-night",
    "vscode_modern",
    "zenburn",
    "zephyrium"
}

return {
    "zaldih/themery.nvim",
    config = function()
        require("themery").setup({
            themes = theme_menu_items,
            livePreview = true,
        })
    end,
}
