[tools]
## Installing neovim with mise breaks the install script.
#  Leaving this here as a reference for a "staging" dir
#  where I can test my config locally, without installing neovim.
# "vfox:mise-plugins/vfox-neovim" = "nightly"

