local function theme(name, colorscheme)
  return {
    name = name,
    colorscheme = colorscheme,
  }
end

return {
  default = "kanagawa-wave",
  themes = {
    theme("Aura Dark", "aura-dark"),
    theme("Aura Dark Soft Text", "aura-dark-soft-text"),
    theme("Aura Soft Dark", "aura-soft-dark"),
    theme("Aura Soft Dark Soft Text", "aura-soft-dark-soft-text"),
    theme("Ayu", "ayu"),
    theme("Bluloco Dark", "bluloco-dark"),
    theme("Bluloco Light", "bluloco-light"),
    theme("Carbonfox", "carbonfox"),
    theme("Catppuccin Frappe", "catppuccin-frappe"),
    theme("Catppuccin Macchiato", "catppuccin-macchiato"),
    theme("Catppuccin Mocha", "catppuccin-mocha"),
    theme("Dawnfox", "dawnfox"),
    theme("Dayfox", "dayfox"),
    theme("Dracula", "dracula"),
    theme("Duskfox", "duskfox"),
    theme("Edge", "edge"),
    theme("EF Owl", "ef-owl"),
    theme("EF Winter", "ef-winter"),
    theme("Eldritch", "eldritch"),
    theme("Horizon Extended", "horizon-extended"),
    theme("Kanagawa Dragon", "kanagawa-dragon"),
    theme("Kanagawa Lotus", "kanagawa-lotus"),
    theme("Kanagawa Wave", "kanagawa-wave"),
    theme("Modus Operandi", "modus_operandi"),
    theme("Modus Vivendi", "modus_vivendi"),
    theme("Monokai", "monokai"),
    theme("Moonfly", "moonfly"),
    theme("NekoNight ArcDark", "nekonight-arcdark"),
    theme("NekoNight Aurora", "nekonight-aurora"),
    theme("NekoNight Day", "nekonight-day"),
    theme("NekoNight Deep Ocean", "nekonight-deep-ocean"),
    theme("NekoNight Doom One", "nekonight-doom-one"),
    theme("NekoNight Dracula", "nekonight-dracula"),
    theme("NekoNight Dracula at Night", "nekonight-dracula-at-night"),
    theme("NekoNight Fire Obsidian", "nekonight-fire-obsidian"),
    theme("NekoNight Material Theme", "nekonight-material-theme"),
    theme("NekoNight Moon", "nekonight-moon"),
    theme("NekoNight Moonlight", "nekonight-moonlight"),
    theme("NekoNight Night", "nekonight-night"),
    theme("NekoNight Noctis Uva", "nekonight-noctis-uva"),
    theme("NekoNight Nord", "nekonight-nord"),
    theme("NekoNight OneDark Deep", "nekonight-onedark-deep"),
    theme("NekoNight Palenight", "nekonight-palenight"),
    theme("NekoNight Shades of Purple", "nekonight-shades-of-purple"),
    theme("NekoNight Shades of Purple Dark", "nekonight-shades-of-purple-dark"),
    theme("NekoNight Sky Blue", "nekonight-sky-blue"),
    theme("NekoNight Space", "nekonight-space"),
    theme("NekoNight Storm", "nekonight-storm"),
    theme("NekoNight Synthwave", "nekonight-synthwave"),
    theme("NekoNight Zenburn", "nekonight-zenburn"),
    theme("Nightfly", "nightfly"),
    theme("Nightfox", "nightfox"),
    theme("Nord", "nord"),
    theme("Nordic", "nordic"),
    theme("Nordfox", "nordfox"),
    theme("OneDark", "onedark"),
    theme("One Monokai", "one_monokai"),
    theme("Oxocarbon", "oxocarbon"),
    theme("Palenightfall", "palenightfall"),
    theme("PaperColor", "PaperColor"),
    theme("Penumbra", "penumbra"),
    theme("Poimandres", "poimandres"),
    theme("Rusty", "rusty"),
    theme("Terafox", "terafox"),
    theme("Tokyo Night Moon", "tokyonight-moon"),
    theme("Tokyo Night Night", "tokyonight-night"),
    theme("Vague", "vague"),
    theme("VSCode Modern", "vscode_modern"),
    theme("Zenburn", "zenburn"),
    theme("Zephyrium", "zephyrium"),
  },
}
