---
## Do the release, run after `prepare-release.yml`
# .github/workflows/create-release.yml
name: Create Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.title == 'Release Prepare PR'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get tag from changelog
        id: tag
        run: |
          TAG=$(grep '^## ' CHANGELOG.md | head -n 1 | awk '{print $2}')
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Create tag
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Zip configs (again, optional, if you want to recreate)
        run: |
          mkdir -p dist
          for dir in config/*/; do
            base=$(basename "$dir")
            zip -r "dist/${base}.zip" "$dir"
          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
