---
# From https://github.com/Allaman/kustomize.nvim/blob/main/.github/workflows/ci.yml
name: CI Release
on:
  workflow_dispatch:

jobs:
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple
          package-name: redjax.nvim

      - uses: actions/checkout@v4

      - name: tag stable versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d stable || true
          git push origin :stable || true
          git tag -a stable -m "Last Stable Release"
          git push origin stable

      ## Zip each config profile ---
      - name: Zip config profiles
        if: ${{ steps.release.outputs.release_created }}
        run: |
          mkdir -p dist
          for dir in config/*/ ; do
            profile=$(basename "$dir")
            zip -r "dist/${profile}.zip" "$dir"
          done

      ## Upload ZIPs as release assets
      - name: Upload release assets
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
