---
## Do the release, run after `prepare-release.yml`
# .github/workflows/create-release.yml
name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Determine new version tag
        id: tag_version
        run: |
          # This example just creates a new tag with timestamp; replace with semver bump logic if needed
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create and push tag
        run: |
          git tag ${{ steps.tag_version.outputs.tag }}
          git push origin ${{ steps.tag_version.outputs.tag }}

      - name: Zip config profiles
        run: |
          mkdir -p dist
          for dir in config/*/; do
            name=$(basename "$dir")
            zip -r "dist/${name}.zip" "$dir"
          done

      - name: Create GitHub release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.tag }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
