---
## Do the release, run after `prepare-release.yml`
name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip config profiles
        run: |
          mkdir -p dist
          for dir in config/*/ ; do
            profile=$(basename "$dir")
            zip -r "dist/${profile}.zip" "$dir"
          done
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
