---
## Do the release, run after `prepare-release.yml`
# .github/workflows/create-release.yml
name: Create Release

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  release:
    if: github.event.pull_request.merged == true && github.event.pull_request.title == 'Release Prepare PR'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create new tag
        id: tag
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Tag and push
        run: |
          git tag ${{ steps.tag.outputs.tag }}
          git push origin ${{ steps.tag.outputs.tag }}

      - name: Zip config profiles
        run: |
          mkdir -p dist
          for dir in config/*/; do
            name=$(basename "$dir")
            zip -r "dist/${name}.zip" "$dir"
          done

      - name: Create GitHub release with assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
