---
## Prepare a release, run this first
# .github/workflows/prepare-release.yml
name: Prepare Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create zip files
        run: |
          mkdir -p dist
          for dir in config/*/; do
            base=$(basename "$dir")
            zip -r "dist/${base}.zip" "$dir"
          done
          ls -l dist

      - name: Create branch and commit zip files
        id: create_branch
        run: |
          BRANCH=release/prepare-$(date +%s)
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

          git checkout -b "$BRANCH"
          git add dist/*.zip

          # Force commit: if no changes, create empty commit so branch differs from main
          if git diff --cached --quiet; then
            git commit --allow-empty -m "chore: prepare release artifacts (empty commit)"
          else
            git commit -m "chore: prepare release artifacts"
          fi

      - name: Push branch
        run: |
          git push --set-upstream origin ${{ steps.create_branch.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.create_branch.outputs.branch }}
          title: Release Prepare PR
          body: This PR prepares the release artifacts.
          base: main
