---
## Prepare a release, run this first
# .github/workflows/prepare-release.yml
name: Prepare Release

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set release branch name
        id: vars
        run: echo "branch=release/$(date +%s)" >> $GITHUB_OUTPUT

      - name: Create ZIPs of each config
        run: |
          mkdir -p dist
          for dir in config/*/; do
            name=$(basename "$dir")
            zip -r "dist/${name}.zip" "$dir"
          done

      - name: Create release branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git switch -c ${{ steps.vars.outputs.branch }}
          cp dist/*.zip .
          git add *.zip
          git commit -m "chore(release): add zipped configs"
          git push origin HEAD

      - name: Create PR to main
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: ${{ steps.vars.outputs.branch }}
          title: "chore: prepare release"
          body: "Zipped configs added to prepare for release"
