---
## Prepare a release, run this first
# .github/workflows/prepare-release.yml
name: Prepare Release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create release preparation commit
        run: |
          # Example: bump version file or add zipped configs, adjust as needed
          echo "Prepare release commit" > prepare.txt
          git add prepare.txt
          git commit -m "chore: prepare release"

      - name: Push branch for PR
        run: |
          git push --force --set-upstream origin release/prepare

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: prepare release"
          branch: release/prepare
          title: Release Prepare PR
          body: This PR prepares the release artifacts.
          base: main
